# Generated by Django 2.2.8 on 2020-02-01 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('desc', models.TextField(max_length=200)),
                ('added_date', models.DateField(default=datetime.date(2020, 2, 1))),
                ('comment', models.TextField(max_length=20)),
                ('created_time', models.DateTimeField(default=datetime.datetime(2020, 2, 1, 16, 45, 5, 616325))),
            ],
        ),
    ]
