# Generated by Django 2.2.8 on 2020-02-01 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 1, 16, 45, 24, 951156)),
        ),
    ]
