# Generated by Django 2.2.8 on 2020-02-01 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20200201_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='created_time',
        ),
        migrations.AddField(
            model_name='todo',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 1, 16, 46, 6, 151649)),
        ),
    ]
